# CloudGuard AI Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudguard-frontend
  namespace: cloudguard-ai
  labels:
    app: cloudguard-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudguard-frontend
  template:
    metadata:
      labels:
        app: cloudguard-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: cloudguard-ai/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudguard-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: INFLUXDB_URL
          value: "http://influxdb-service:8086"
        - name: AI_SERVICE_URL
          value: "http://ai-service:8001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cloudguard-ai
  labels:
    app: cloudguard-frontend
spec:
  selector:
    app: cloudguard-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
