# Horizontal Pod Autoscaler for Frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudguard-frontend-hpa
  namespace: cloudguard-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudguard-frontend
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min

---
# Custom Metrics for Application-Level Scaling
apiVersion: v1
kind: Service
metadata:
  name: cloudguard-metrics
  namespace: cloudguard-ai
  labels:
    app: cloudguard-frontend
spec:
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: cloudguard-frontend
